 <b>NumPy and the Python ecosystem<b>

In [1]:
import numpy as np

<b>Arrays vs. Python lists<b>

- While Python lists can include many different data types, all of the elements in a NumPy array must be the same data type
- Having only a single data type also means that a NumPy array takes up less space in memory than the same information      would if stored as a Python list.

<b>Creating arrays from scratch in 3 ways<b>

<b>1. np.zeros()<b>

In [3]:
np.zeros((5,3)) #Tuple that creating an array with 5 rows and three columns with 0 values

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<b>2. np.random.random() </b>

In [4]:
np.random.random((2,4)) # creating a array with random values (np.random)-numpy module  (.random) - function name

array([[0.46739296, 0.99384911, 0.91101586, 0.65660951],
       [0.44965495, 0.83912475, 0.77517548, 0.95961714]])

<b>3. np.arange()   </b>

 - It is particullarly usedfor plotting

In [6]:
np.arange(3,10) # np-dot-arange creates an array of sequential integers #The start value is included in the output array, but the stop value is not. The start value can be omitted if the range begins with zero. If a third argument is passed, it is interpreted as the step value.

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(4)

array([0, 1, 2, 3])

In [8]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

---------------------------------------

In [ ]:
To conver a list to numpy array 
syntax :
         new_name = np.array(list_name)

<b> Scatter plot<b>

<b> Array Dimensionality <b>

- a two-dimensional array is called a matrix.
- an array with three or more dimensions is called a tensor.

<b>array_name.shape</b>
- dot-shape describes the shape of an array and returns a tuple of the length of each dimension. A shape of (3, 5) indicates a 2D array with three rows and five columns.

<b> array_name.flatten()</b>

- flatten()  it takes all array elements and puts them in just one dimension inside a 1D array.

<b> array_name.reshape()</b>
- The dot-reshape method allows us to redefine the shape of an array without changing the elements that make up the array

<b>np.stack(arr1,arr2 )</b>
- It stack the arrays in the passing order

-----------------------

<b> Numpy Datatypes</b>

dtype is an attribute for datatype


In [ ]:
Type conversion - .astype(np.int64)

Type coercion - converting all the data in the array in the same type [numbers to strings][It will take the big datatype and convert the other data into it]

--------------------------------------

<b>Applications of numpy</b>

- Numpy has contiguous memory , differ from list doesnt have it
- Effective cache utilization
- SIMBD Vector proccessing

<b>The basics<b>

In [23]:
a1 = np.array([1,2,3]) #One-dimensional array
print(a1)

[1 2 3]


In [20]:
a = np.array([[1.1,2.1,3.1],[1.0,2.0,3.0]]) #two-dimensional array
print(a)

[[1.1 2.1 3.1]
 [1.  2.  3. ]]


In [25]:
#Get dimension
print(a.ndim)
a1.ndim

2


1

In [26]:
#Get shape
a1.shape

(3,)

In [27]:
a.shape

(2, 3)

In [29]:
#Get type
a.dtype

a1.dtype

dtype('int32')

In [31]:
#Initializing the type
a1 = np.array([1,2,3],dtype="int8") #One-dimensional array
print(a1)
a1.dtype

[1 2 3]


dtype('int8')

In [33]:
#Get size
a1.itemsize # 8bits = 1byte

1

In [34]:
#Get total size
a1.nbytes #based on dtype and bytes

3

<b> Accesssing / changing specific elements in rows,columns etcc.. </b>

In [36]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [37]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
#Get specific element [row,column]
a[1,-1]

10

In [43]:
a[1,4]

10

In [45]:
#Get a specific row
a[0, ]

array([1, 2, 3, 4, 5])

In [49]:
#Get a specific column
a[:,3]

array([4, 9])

In [51]:
#[start:stop:step]
a[0,1::]

array([2, 3, 4, 5])

In [52]:
# Reassigning or updating
a[0,3] = 100

In [53]:
a

array([[  1,   2,   3, 100,   5],
       [  6,   7,   8,   9,  10]])

In [55]:
a[:,2]=5

In [56]:
a

array([[  1,   2,   5, 100,   5],
       [  6,   7,   5,   9,  10]])

In [57]:
new_ = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [59]:
new_[:2,2]

array([3, 7])

<B>Initializing Different types of arrays</b>

In [60]:
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [61]:
np.ones((3,3),dtype="int32")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [62]:
#Any other number
# np.full(shape,number)
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [63]:
#Any other number full_like ##Using the already available array
np.full_like(a,10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [67]:
# Random decimal number
a = np.random.rand(2,3) 
b = np.random.random((2,2)) #takes tuple as single value argument

In [65]:
b

array([[0.17537105, 0.10405271],
       [0.03786272, 0.28872527]])

In [68]:
a

array([[0.00567922, 0.53415509, 0.13345347],
       [0.88689858, 0.54597745, 0.92279528]])

In [69]:
np.random.random_sample(a.shape)

array([[0.98828252, 0.74023036, 0.45229144],
       [0.17090035, 0.1781373 , 0.27677573]])

In [75]:
# Random Integer values
np.random.randint(2,size=(3,3))

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [76]:
np.random.randint(3,8,size=(3,3))

array([[6, 7, 5],
       [3, 3, 6],
       [7, 6, 4]])

In [83]:
# Identity matrix
b1=np.identity(3,dtype="int8")
print(b1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [86]:
#Repeat the array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [89]:
res = np.ones((5,5),dtype="int8")

In [91]:
print(res)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [92]:
res[2,2]=9

In [93]:
print(res)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 9 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [94]:
res[1,1:4] =0
res[2,1:4:2] =0
res[3,1:4] =0

In [95]:
print(res)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [100]:
#alternate way
z = np.zeros((3,3))
print(z)
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [101]:
res[1:4,1:4] =z

In [103]:
print(res)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be careful with copying variables!!

In [105]:
a=np.array([1,2,3])
b=a
print(a)

[1 2 3]


In [107]:
print(b)

[1 2 3]


In [108]:
b[0]=100
print(b)

[100   2   3]


In [109]:
print(a) ##it change the original value where it is copied

[100   2   3]


In [110]:
##TO prevent that use .copy()
b = a.copy()

------------------------------------------------

<b>Mathematics</b>

In [118]:
a=np.array((1,2,3))


In [113]:
a+2 #-,*,/

array([3, 4, 5])

In [114]:
b=np.array([1,2,3])
res=a+b

In [115]:
res

array([2, 4, 6])

In [119]:
a**2

array([1, 4, 9], dtype=int32)

<b>Trignometry</b>

In [121]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [134]:
np.cos(a)

array([[0.5405, 0.5405, 0.5405],
       [0.5405, 0.5405, 0.5405]], dtype=float16)

In [123]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654])

<b>Linera Algebra</b>

In [126]:
a=np.ones([2,3],dtype="int8") #therow value and the column of another should be same
print(a)

[[1 1 1]
 [1 1 1]]


In [128]:
b=np.full([3,2],2,dtype="int8")
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [130]:
res = np.matmul(a,b) #matrix multiply
print(res)

[[6 6]
 [6 6]]


In [133]:
#Find the determinant
c= np.identity(3)
np.linalg.det(c)

1.0

<b> Statistics</b>

In [135]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
np.min(stats,axis=1)

array([1, 4])

In [140]:
np.min(stats,axis=0)

array([1, 2, 3])

In [141]:
np.min(stats) #minimum value

1

In [142]:
np.max(stats) #maximum value

6

In [143]:
np.max(stats,axis=1)

array([3, 6])

In [144]:
np.sum(stats)

21

In [145]:
np.sum(stats,axis=1)

array([ 6, 15])

<b>Reorganizing arrays</b>

In [148]:
before = np.array([[1,2,3,4],[12,3,4,5]])
print(before)

[[ 1  2  3  4]
 [12  3  4  5]]


In [154]:
after = before.reshape(4,2)
print(after)

[[ 1  2]
 [ 3  4]
 [12  3]
 [ 4  5]]


In [155]:
#Vertically Stacking vectors
v1 =np.array([1,2,3,4])
v2 =np.array([5,6,7,8])

res = np.vstack([v1,v2,v2,v1])

In [157]:
print(res)

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [159]:
#Horizontal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

res1=np.hstack((h1,h2))

In [160]:
print(res1)

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


<b>Miscellanous</b>

<b>Load a data from a file</b>

In [166]:
file_data=np.genfromtxt('numpy-demo.txt',delimiter=",")

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [165]:
file_data.astype("int8")

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]], dtype=int8)

##### Boolean masking and advance masking

In [167]:
file_data > 50

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [168]:
file_data > 0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [170]:
file_data [file_data > 3]

array([4., 5., 4., 5., 4., 5., 4., 5.])

In [173]:
#You can index with a list
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,8]]

array([2, 4, 9])

In [176]:
np.any(file_data > 50, axis=0)

array([False, False, False, False, False])

In [177]:
np.all(file_data > 50, axis=0)

array([False, False, False, False, False])